# Generated by Django 5.0.4 on 2024-05-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxInventory',
            fields=[
                ('box_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('q_per_box', models.IntegerField()),
                ('no_of_box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('location_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('container_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('no_of_box', models.IntegerField()),
                ('to_location', models.CharField(max_length=255)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.boxinventory')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouselocation')),
            ],
        ),
        migrations.AddField(
            model_name='boxinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('container', models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='inventory.container')),
            ],
        ),
        migrations.CreateModel(
            name='OpenInventory',
            fields=[
                ('open_inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouselocation')),
            ],
        ),
        migrations.CreateModel(
            name='Gateout',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('to', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.openinventory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouselocation')),
            ],
        ),
        migrations.AddField(
            model_name='boxinventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouselocation'),
        ),
    ]
