# Generated by Django 5.0.4 on 2024-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxinventory',
            name='box_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
