# Generated by Django 5.0.4 on 2024-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_boxinventory_box_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
