# Generated by Django 5.0.4 on 2024-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_container_container_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateout',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
