# Generated by Django 5.0.4 on 2024-05-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_shipping_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
